# DataSourse
spring.datasource.url: jdbc:mysql://localhost:3306/test_task?serverTimezone=Europe/Moscow&createDatabaseIfNotExist=true&useSSL=false
spring.datasource.username: root
spring.datasource.password: test

# Hibernate
spring.jpa.database-platform: org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto: none

# инициализация базы данных из файлов .sql
spring.datasource.initialization-mode: always
spring.datasource.schema: classpath:database-init/schema.sql